### ISSUE TITLE
Feature request: Repo for updating clusterctl

### ISSUE THREAD

**Issue by ScrumpyJack** [burtyb/clusterhat-image#6]
Downloading new Clusterhat images means wiping my cluster and starting from scratch, so i upgraded stretch to buster using apt. It would be nice to have a way to update the clusterctl  and anything else you've included using some custom repos.

Also, looking forward to a python3 compatible clusterctl script. clusterctl is currently the last thing on my Cluster that requires python2 :)

**Comment by ScrumpyJack** [comment]
Oops, I now realise that my cluster hat PI Zero's aren't getting an IP address after updating the RPi3 Cluster Controller to buster. (Even though I made sure I kept the dhcpd.conf file)

**Comment by burtyb** [comment]
The Buster based image came some major changes on the Cluster HAT side - libcomposite is now used to create the USB Gadget devices and a systemd service rather than using the old g_cdc module, the udev rules are also different, etc.

To manually upgrade it you could probably  go through the diff https://github.com/burtyb/clusterhat-image/commit/c85bfa273081aaf10ae6b495f942f13f14f7bc14#diff-85db58e85eae1f52b0b55b1075b37398 but you would also need to make changes on the Pi Zeros too.

**Comment by ScrumpyJack** [comment]
Ok, I'll start from scratch, seems sensible
